# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8810574910598d686fb31fd1465ede026a12b9edd4a1f08b4beb65948f8a172abcc043cd8ac5925b4b98180c06c71fe59cbf9cca3b0da51422a7bac8cc0f8227

test:
  secret_key_base: ba45767a59984cd230a92ce45fb2e58b98243cc884d97160044f9a05f59603acdf048251cc3f25b0e68d5139e1100eca419876048117180c38a71e25a17a91c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
